# Generated by Django 4.1.5 on 2023-01-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_tag_commentaire_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_add', '-date_update']},
        ),
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['-date_add', '-date_update']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-date_add', '-date_update']},
        ),
        migrations.RemoveField(
            model_name='avis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='status',
        ),
    ]
