# Generated by Django 4.1.5 on 2023-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_avis_options_alter_commentaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
