# Generated by Django 4.1.5 on 2023-01-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_tag_alter_produit_categorie_alter_produit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
