# Generated by Django 4.1.5 on 2023-02-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
