# Generated by Django 4.1.5 on 2023-02-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
